- name: configure backend
  hosts: backend
  become: yes 
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.dnf:
      name: dnf
      state: latest
          