- name: configure backend
  hosts: backend
  become: yes 
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.dnf:
      name: dnf
      state: latest
  # useradd expense

  - name: adding user
    ansible.builtin.user:
      name: expense

  #mkdir /app 
  - name: app dir
    ansible.builtin.file:
      path: /app
      state: directory   

  - name: download and unzip the backend 
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /app 
      remote_src: yes             