- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable node js
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.dnf:
      name: "{{item}}" 
      state: latest
    loop:
    - nodejs
    - mysql  

  - name: install PIP
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9  

  - name: user add expense
    ansible.builtin.user:
      name: expense

  - name: creating app dir
    ansible.builtin.file:
      path: /app
      state: directory        

  - name: download code into app
    ansible.builtin.unarchive:
     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     dest: /app
     remote_src: yes   

  - name: npm install
    ansible.builtin.command: "npm install"
    args:
     chdir: /app   

  - name: copying backend service code
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service  

