- name: configure db server
  hosts: frontend
  become: yes 
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: yes 
  #rm -rf /usr/share/nginx/html/*
  - name: remove html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: remove html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory      

  - name: unarchieve 
    ansible.builtin.unarchive:
     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
     dest: /usr/share/nginx/html 
     remote_src: yes    
